#!/usr/bin/python3
# -*- coding: UTF-8 -*-

from skl_shared_qt.localize import _
import skl_shared_qt.shared as sh

# Last update: June 2021
SUBJECTS = [['Agriculture'
            ,'Agrochemistry'
            ,'Agronomy'
            ,'Animal husbandry'
            ,'Beekeeping'
            ,'Fertilizers'
            ,'Fish farming (pisciculture)'
            ,'Floriculture'
            ,'Fodder'
            ,'Gardening'
            ,'Greenhouse technology'
            ,'Horse breeding'
            ,'Horticulture'
            ,'Meat processing'
            ,'Melioration'
            ,'Milk production'
            ,'Pest control'
            ,'Phytophathology'
            ,'Poultry farming'
            ,'Selective breeding'
            ,'Soil science'
            ,'Wine growing'
            ,'Zootechnics'
            ]
           ,['Art and culture (n.e.s.)'
            ,'Art'
            ,'Ballet'
            ,'Calligraphy'
            ,'Choreography'
            ,'Circus'
            ,'Comics'
            ,'Cultural studies'
            ,'Dancing'
            ,'Design'
            ,'Fashion'
            ,'Librarianship'
            ,'Manga'
            ,'Museums'
            ,'Music'
            ,'Musical instruments'
            ,'Painting'
            ,'Rhetoric'
            ,'Sculpture'
            ,'Tauromachy'
            ,'Theatre'
            ,'Titles of works of art'
            ]
           ,['Auxilliary categories (editor use only)'
            ,'American English'
            ,'British English'
            ,'Loan translation'
            ,'Meaning 1'
            ,'Meaning 2'
            ,'Meaning 3'
            ,'Misused'
            ,'Old orthography'
            ,"Translator's false friend"
            ]
           ,['Aviation'
            ,'Aerial photography and topography'
            ,'Aeronautics'
            ,'Airports and air traffic control'
            ,'Airships'
            ,'Aviation medicine'
            ,'Helicopters'
            ,'Hydroplanes'
            ,'ICAO'
            ,'Military aviation'
            ,'Navigation'
            ]
           ,['Biology'
            ,'Acridology'
            ,'Ampelography'
            ,'Amphibians and reptiles'
            ,'Anatomy'
            ,'Bioacoustics'
            ,'Biochemistry'
            ,'Biogeography'
            ,'Biophysics'
            ,'Biotaxy'
            ,'Biotechnology'
            ,'Botany'
            ,'Carcinology'
            ,'Chalcidology'
            ,'Cytogenetics'
            ,'Cytology'
            ,'Embryology'
            ,'Entomology'
            ,'Ethology'
            ,'Evolution'
            ,'Genetic engineering'
            ,'Genetics'
            ,'Geobotanics'
            ,'Helminthology'
            ,'Herpetology (incl. serpentology)'
            ,'Hydrobiology'
            ,'Ichthyology'
            ,'Malacology'
            ,'Mammals'
            ,'Microbiology'
            ,'Molecular biology'
            ,'Molecular genetics'
            ,'Mycology'
            ,'Ornithology'
            ,'Paleobotany'
            ,'Paleontology'
            ,'Paleozoology'
            ,'Palynology'
            ,'Protozoology'
            ,'Zoology'
            ]
           ,['Building materials'
            ,'Astringents'
            ,'Bricks'
            ,'Cement'
            ,'Ceramic tiles'
            ,'Concrete'
            ,'Drywall'
            ,'Paint, varnish and lacquer'
            ,'Refractory materials'
            ]
           ,['Business'
            ,'Advertising'
            ,'Alternative dispute resolution'
            ,'Business style'
            ,'Commerce'
            ,'Companies & Partnerships'
            ,'Consulting'
            ,'Contracts'
            ,'Corporate governance'
            ,'Electronic commerce'
            ,'Exhibitions'
            ,'Human resources'
            ,'Investment'
            ,'Legal entity types (business legal structures)'
            ,'Offshore companies'
            ,'Public relations'
            ,'Trade classification'
            ,'Trademark'
            ]
           ,['Chemical industry'
            ,'Agrochemistry'
            ,'Astringents'
            ,'Chemical fibers'
            ,'Dyes'
            ,'Enameling'
            ,'Forest chemistry'
            ,'Galvanizing'
            ,'Galvanoplasty'
            ,'Material safety data sheet'
            ,'Plastics'
            ,'Polymers'
            ,'Resins'
            ,'Silicate industry'
            ,'Stratified plastics'
            ]
           ,['Chemistry'
            ,'Agrochemistry'
            ,'Alkaloids'
            ,'Biochemistry'
            ,'Chemical compounds'
            ,'Chemical nomenclature'
            ,'Chromatography'
            ,'Colloid chemistry'
            ,'Distillation'
            ,'Dyalysis'
            ,'Electrochemistry'
            ,'Electrolysis'
            ,'Forest chemistry'
            ,'Geochemistry'
            ,'Inorganic chemistry'
            ,'Laboratory equipment'
            ,'Nuclear chemistry'
            ,'Organic chemistry'
            ,'Physical chemistry'
            ,'Spectroscopy'
            ]
           ,['Cinematography'
            ,'Animation and animated films'
            ,'Cinema equipment'
            ,'Film lighting equipment'
            ,'Film processing'
            ,'Filming equipment'
            ,'Magnetic image recording'
            ,'Narrow film'
            ,'Photographical sound recording'
            ,'Projectors'
            ,'Sound engineering'
            ,'Sound recording'
            ]
           ,['Collecting'
            ,'Numismatics'
            ,'Phaleristics'
            ,'Philately / stamp collecting'
            ]
           ,['Communications'
            ,'Antennas and waveguides'
            ,'E-mail'
            ,'Internet'
            ,'Mobile and cellular communications'
            ,'Postal service'
            ,'Radio'
            ,'Satellite communications'
            ,'Short message service'
            ,'Telecommunications'
            ,'Telegraphy'
            ,'Telemechanics'
            ,'Telephony'
            ]
           ,['Companion animals'
            ,'Dog breeding'
            ,'Felinology'
            ,'Pets'
            ]
           ,['Computing'
            ,'ASCII'
            ,'Artificial intelligence'
            ,'Chat and Internet slang'
            ,'Computer games'
            ,'Computer graphics'
            ,'Computer networks'
            ,'Computer security'
            ,'Computing slang'
            ,'Data processing'
            ,'Databases'
            ,'E-mail'
            ,'File extension'
            ,'Hacking'
            ,'Information security'
            ,'Information technology'
            ,'Internet'
            ,'Microsoft'
            ,'Neural networks'
            ,'Office equipment'
            ,'Operation systems'
            ,'Programming'
            ,'SAP'
            ,'SAP finance'
            ,'SAP tech.'
            ,'Social media'
            ,'Software'
            ]
           ,['Construction'
            ,'Architecture'
            ,'Bridge construction'
            ,'Building structures'
            ,'Dams'
            ,'Foundation engineering'
            ,'Heavy equipment vehicles'
            ,'Landscaping'
            ,'Municipal planning'
            ,'Paint work'
            ,'Pipelines'
            ,'Plumbing'
            ,'Reinforced concrete'
            ,'Road construction'
            ,'Road surface'
            ,'Road works'
            ,'Soil mechanics'
            ,'Stonemasonry'
            ,'Tools'
            ,'Tunneling'
            ,'Valves'
            ,'Welding'
            ,'Windows'
            ,'Wiring'
            ]
           ,['Cooking'
            ,'Beverages'
            ,'Confectionery'
            ,'Spices'
            ]
           ,['Countries and regions'
            ,'Afghanistan'
            ,'Africa'
            ,'Algeria'
            ,'Andalusia'
            ,'Antilles'
            ,'Aragon'
            ,'Argentina'
            ,'Asturias'
            ,'Australia'
            ,'Austria'
            ,'Belarus'
            ,'Bolivia'
            ,'Brazil'
            ,'Canada'
            ,'Central America'
            ,'Chile'
            ,'China'
            ,'Columbia'
            ,'Costa Rica'
            ,'Cuba'
            ,'Cyprus'
            ,'Dominican Republic'
            ,'European Union'
            ,'France'
            ,'Galicia'
            ,'Germany'
            ,'Guatemala'
            ,'India'
            ,'Iran'
            ,'Israel'
            ,'Japan'
            ,'Kazakhstan'
            ,'Kyrgyzstan'
            ,'Morocco'
            ,'Netherlands'
            ,'Northern Ireland'
            ,'Panama'
            ,'Peru'
            ,'Philippines'
            ,'Russia'
            ,'Scotland'
            ,'South America'
            ,'South Asia'
            ,'Spain'
            ,'Taiwan'
            ,'Turkey'
            ,'Ukraine'
            ,'United Kingdom'
            ,'United States'
            ,'Venezuela'
            ,'Wales'
            ,'West Indies'
            ]
           ,['Crafts'
            ,'Cooperage'
            ,'Spinning'
            ,'Weaving'
            ]
           ,['Dialectal'
            ,'Beijing dialect'
            ,'Cantonese'
            ,'Derbet language'
            ,'Eastern Chinese'
            ,'Jamaican English'
            ,'Middle Chinese'
            ,'Northeastern Mandarin'
            ,'Northern Chinese'
            ,'Ritual'
            ,'Salvadoran Spanish'
            ,'Shanghainese'
            ,'Sicilian'
            ,'Southern Chinese'
            ,'Torgut language'
            ,'Uruguayan Spanish'
            ,'Vienna dialect'
            ]
           ,['Economy'
            ,'Commerce'
            ,'Employment'
            ,'Foreign trade'
            ,'Insurance'
            ,'International trade'
            ,'Investment'
            ,'Marketing'
            ,'Political economy'
            ,'Trade classification'
            ,'World trade organization'
            ]
           ,['Education'
            ,'Pedagogics'
            ,'Physical sciences'
            ,'School and university subjects'
            ,'Social science'
            ,'University'
            ]
           ,['Electrical engineering'
            ,'Cables and cable production'
            ,'Electric machinery'
            ,'Electric motors'
            ,'Electricity'
            ,'Isolation'
            ,'Measuring instruments'
            ,'Power electronics'
            ,'Power system protection'
            ,'Semiconductors'
            ,'Superconductivity'
            ,'Tools'
            ,'Transformers'
            ]
           ,['Electronics'
            ,'Cathode-ray tubes'
            ,'High frequency electronics'
            ,'Integrated circuits'
            ,'Microelectronics'
            ,'Power electronics'
            ,'Printed circuit boards'
            ,'Vacuum tubes'
            ]
           ,['Emotional values'
            ,'Affectionate'
            ,'Avuncular'
            ,'Contemptuous'
            ,'Derogatory'
            ,'Disapproving'
            ,'Emotive'
            ,'Gloomy'
            ,'Humorous / Jocular'
            ,'Ironical'
            ,'Laudatory'
            ,'Pejorative'
            ,'Polite'
            ,'Pompous'
            ,'Respectful'
            ,'Rude'
            ,'Sarcastical'
            ]
           ,['Energy industry'
            ,'Bioenergy'
            ,'Electricity generation'
            ,'Energy distribution'
            ,'Energy system'
            ,'Hydroelectric power stations'
            ,'Nuclear and fusion power'
            ,'Power lines'
            ,'Power system protection'
            ,'Solar power'
            ,'Thermal Energy'
            ,'Transformers'
            ,'Wind Energy'
            ]
           ,['Engineering'
            ,'Air conditioners'
            ,'Architecture'
            ,'Bionics'
            ,'Building structures'
            ,'Design'
            ,'Drawing'
            ,'Heat exchangers'
            ,'Heating'
            ,'Hydraulic engineering'
            ,'Hydraulics'
            ,'Hydromechanics'
            ,'Landscaping'
            ,'Municipal planning'
            ,'Pipelines'
            ,'Radiogeodesy'
            ,'Refrigeration'
            ,'Seismic resistance'
            ,'Sewage and wastewater treatment'
            ,'Soil mechanics'
            ,'Strength of materials'
            ,'Surveying'
            ,'Thermal engineering'
            ,'Tunneling'
            ,'Valves'
            ,'Ventilation'
            ,'Water supply'
            ]
           ,['Finances'
            ,'Accounting'
            ,'American stock exchange'
            ,'Audit'
            ,'Banking'
            ,'Charities'
            ,'Currencies and monetary policy'
            ,'Digital and cryptocurrencies'
            ,'European Bank for Reconstruction and Development'
            ,'Foreign exchange market'
            ,'Insurance'
            ,'International Monetary Fund'
            ,'Investment'
            ,'NASDAQ'
            ,'New York Stock Exchange'
            ,'Offshore companies'
            ,'SAP finance'
            ,'Securities'
            ,'Stock Exchange'
            ]
           ,['Folklore'
            ,'Proverb'
            ,'Puzzle'
            ,'Saying'
            ]
           ,['Food industry'
            ,'Alcohol distilling'
            ,'Bakery'
            ,'Beverages'
            ,'Brewery'
            ,'Canning'
            ,'Champagne and sparkling wines'
            ,'Cheesemaking (caseiculture)'
            ,'Coffee'
            ,'Confectionery'
            ,'Fat-and-oil industry'
            ,'Fermentation'
            ,'Flour production'
            ,'Glass container manufacture'
            ,'Groceries'
            ,'Meat processing'
            ,'Milk production'
            ,'Starch industry'
            ,'Sugar production'
            ,'Wine tasting'
            ,'Winemaking'
            ]
           ,['Foreign affairs'
            ,'Diplomacy'
            ,'Foreign policy'
            ,'Immigration and citizenship'
            ,'International relations'
            ]
           ,['Games (other than sports)'
            ,'Billiards'
            ,'Bowling'
            ,'Bridge (card game)'
            ,'Card games'
            ,'Checkers'
            ,'Chess'
            ,'Computer games'
            ,'Cricket'
            ,'Darts'
            ,'Dice'
            ,'Gambling'
            ,'Golf'
            ,'Mahjong'
            ,'Tabletop games'
            ]
           ,['Geography'
            ,'Administrative geography'
            ,'Aerial photography and topography'
            ,'Antarctic'
            ,'Cartography'
            ,'Climatology'
            ,'Demography'
            ,'Earth sciences'
            ,'Ethnography'
            ,'Ethnology'
            ,'Geomorphology'
            ,'Hydrography'
            ,'Hydrology'
            ,'Hydrometry'
            ,'Ice formation'
            ,'Limnology'
            ,'Meteorology'
            ,'Oceanography (oceanology)'
            ,'Remote sensing'
            ,'Seismology'
            ,'Soil science'
            ,'Topography'
            ]
           ,['Geology'
            ,'Crystallography'
            ,'Engineering geology'
            ,'Gemmology'
            ,'Geochemistry'
            ,'Geochronology'
            ,'Geomechanics'
            ,'Geomorphology'
            ,'Geophysics'
            ,'Glaciology'
            ,'Hydrogeology'
            ,'Lithology'
            ,'Mineral classification'
            ,'Mineral products'
            ,'Mineralogy'
            ,'Petrography'
            ,'Reservoir simulation'
            ,'Sedimentology'
            ,'Seismology'
            ,'Soil science'
            ,'Spectroscopy'
            ,'Speleology'
            ,'Stratigraphy'
            ,'Tectonics'
            ,'Volcanology'
            ]
           ,['Government, administration and public services'
            ,'Customs'
            ,'Health care'
            ,'Penitentiary system'
            ,'Police'
            ,'Public utilities'
            ,'Taxes'
            ,'Welfare & Social Security'
            ]
           ,['Grammatical labels'
            ,'Abbreviation'
            ,'Affectionate'
            ,'Augmentative'
            ,'Collective'
            ,'Diminutive'
            ,'Exclamation'
            ,'Iimitative (onomatopoeic)'
            ]
           ,['Historical'
            ,'Anthropology'
            ,'Archaeology'
            ,'Classical antiquity (excl. mythology)'
            ,'Cultural studies'
            ,'East Germany (history)'
            ,'Egyptology'
            ,'Genealogy'
            ,'Heraldry'
            ,'Historical figure'
            ,'Palaeography'
            ,'Socialism'
            ,'Soviet'
            ]
           ,['Hobbies and pastimes'
            ,'Angling (hobby)'
            ,'Handicraft'
            ,'Model sports'
            ]
           ,['Human rights activism'
            ,'LGBT'
            ]
           ,['Industry'
            ,'Industrial hygiene'
            ,'Machine tools'
            ,'Materials science'
            ,'Mechanic engineering'
            ,'Metalworking'
            ,'Press equipment'
            ,'Silicate industry'
            ,'Stamping'
            ,'Tobacco industry'
            ,'Waste management'
            ,'Wire drawing'
            ]
           ,['Jargon and slang'
            ,'Black slang'
            ,'Chat and Internet slang'
            ,'Cockney rhyming slang'
            ,'College vernacular'
            ,'Computing slang'
            ,'Criminal jargon'
            ,'Drug-related slang'
            ,'Jargon'
            ,'Latin American slang'
            ,'Military lingo'
            ,'Police jargon'
            ,'Prison slang'
            ,'Professional jargon'
            ,'School'
            ,'Slang'
            ,'Spanish-American'
            ,'Verlan'
            ,'Youth slang'
            ]
           ,['Languages'
            ,'Albanian language'
            ,'Ancient French'
            ,'Ancient Greek'
            ,'Ancient Hebrew'
            ,'Arabic language'
            ,'Belarusian language'
            ,'Bulgarian language'
            ,'Chinese'
            ,'Czech'
            ,'Danish'
            ,'Dutch'
            ,'English'
            ,'Esperanto'
            ,'Estonian language'
            ,'Finnish language'
            ,'French'
            ,'Gaelic'
            ,'German'
            ,'Greek'
            ,'Hawaii'
            ,'Hebrew'
            ,'Hindi'
            ,'Hungarian Language'
            ,'Iceland'
            ,'Irish'
            ,'Italian'
            ,'Japanese language'
            ,'Korean'
            ,'Latin'
            ,'Malay'
            ,'Manchu language'
            ,'Maori'
            ,'Moldavian'
            ,'Mongolian'
            ,'Norway'
            ,'Persian'
            ,'Polish'
            ,'Portuguese'
            ,'Romanian'
            ,'Russian language'
            ,'Sanskrit'
            ,'Scandinavian'
            ,'Spanish'
            ,'Swedish'
            ,'Tatar'
            ,'Thai'
            ,'Tibetan'
            ,'Turk'
            ,'Turkish language'
            ,'Ukrainian language'
            ,'Vietnamese'
            ,'Yiddish'
            ]
           ,['Law'
            ,'Administrative law'
            ,'Alternative dispute resolution'
            ,'Antitrust law'
            ,'Bills'
            ,'Civil law'
            ,'Civil procedure'
            ,'Common law (Anglo-Saxon legal system)'
            ,'Contracts'
            ,'Copyright'
            ,'Court (law)'
            ,'Criminal law'
            ,'Economic law'
            ,'Inheritance law'
            ,'International law'
            ,'Labor law'
            ,'Legal theory'
            ,'Maritime law & Law of the Sea'
            ,'Notarial practice'
            ,'Patents'
            ,'Private international law'
            ,'Procedural law'
            ,'Public law'
            ]
           ,['Law enforcement'
            ,'Combating corruption'
            ,'Criminology'
            ,'Dactyloscopy'
            ,'Explosives'
            ,'Federal Bureau of Investigation'
            ,'Forensic medicine'
            ,'Forensics'
            ,'Intelligence and security services'
            ,'Organized crime'
            ,'Penitentiary system'
            ,'Police'
            ,'Procedural law'
            ]
           ,['Life sciences'
            ,'Allergology'
            ,'Anesthesiology'
            ,'Bacteriology'
            ,'Cardiology'
            ,'Dermatology'
            ,'Dietology'
            ,'Endocrinology'
            ,'Epidemiology'
            ,'Gastroenterology'
            ,'Hematology'
            ,'Histology'
            ,'Immunology'
            ,'Logopedics'
            ,'Mammalogy'
            ,'Nephrology'
            ,'Neurology'
            ,'Oncology'
            ,'Ophthalmology'
            ,'Orthopedics'
            ,'Parasitology'
            ,'Pathology'
            ,'Pharmacology'
            ,'Physiology'
            ,'Psychiatry'
            ,'Pulmonology'
            ,'Radiobiology'
            ,'Radiology'
            ,'Sexology'
            ,'Teratology'
            ,'Toxicology'
            ,'Transplantology'
            ,'Traumatology'
            ,'Urology'
            ,'Venereology'
            ,'Virology'
            ]
           ,['Light industries'
            ,'Clothing'
            ,'Footwear'
            ,'Haberdashery'
            ,'Knitted goods'
            ,'Leather'
            ,'Sewing and clothing industry'
            ,'Textile industry'
            ]
           ,['Linguistics'
            ,'Grammar'
            ,'Morphology'
            ,'Neurolinguistics'
            ,'Phonetics'
            ,'Phonology'
            ,'Pragmatics'
            ,'Psycholinguistics'
            ,'Semantics'
            ,'Semiotics'
            ,'Sociolinguistics'
            ,'Stylistics'
            ,'Syntax'
            ,'Tagmemics'
            ,'Typology'
            ]
           ,['Literature'
            ,'Fairy tales'
            ,'Fantasy and science fiction'
            ,'Librarianship'
            ,'Poetry (terminology)'
            ,'Quotes and aphorisms'
            ,'Screenwriting'
            ,'Titles of works of art'
            ]
           ,['Logistics'
            ,'International transportation'
            ,'Loading equipment'
            ,'Procurement'
            ,'Warehouse'
            ]
           ,['Machinery and mechanisms'
            ,'Automated equipment'
            ,'Ball bearings'
            ,'Combustion gas turbines'
            ,'Electric machinery'
            ,'Electric motors'
            ,'Electric traction'
            ,'Elevators'
            ,'Engines'
            ,'Gear train'
            ,'Jet engines'
            ,'Machine components'
            ,'Pneumatics'
            ,'Pumps'
            ,'Turbines'
            ,'Watchmaking'
            ]
           ,['Management'
            ,'Corporate governance'
            ,'Human resources'
            ,'Labor organization'
            ,'Project management'
            ,'Risk Management'
            ]
           ,['Martial arts and combat sports'
            ,'Aikido'
            ,'Boxing'
            ,'Judo'
            ,'Karate'
            ,'Sumo'
            ,'Taekwondo'
            ,'Wrestling'
            ,'Wushu'
            ]
           ,['Mass media'
            ,'Advertising'
            ,'Internet'
            ,'Journalism (terminology)'
            ,'Radio'
            ,'Television'
            ]
           ,['Mathematics'
            ,'Algebra'
            ,'Applied mathematics'
            ,'Econometrics'
            ,'Geometry'
            ,'Gravimetry'
            ,'Mathematical analysis'
            ,'Statistics'
            ,'Topology'
            ]
           ,['Medical'
            ,'AIDS'
            ,'Anesthesiology'
            ,'Aviation medicine'
            ,'Chromatography'
            ,'Clinical trial'
            ,'Deafblindness'
            ,'Dentistry'
            ,'Diseases'
            ,'Drug name'
            ,'Drugs and addiction medicine'
            ,'Electromedicine'
            ,'Emergency medical care'
            ,'Gastroenterology'
            ,'Gynecology'
            ,'Health care'
            ,'Laboratory equipment'
            ,'Laser medicine'
            ,'Logopedics'
            ,'Neurosurgery'
            ,'Nursing'
            ,'Obstetrics'
            ,'Oncology'
            ,'Ophthalmology'
            ,'Optometry'
            ,'Orthopedics'
            ,'Pediatrics'
            ,'Pharmacy'
            ,'Physiotherapy'
            ,'Psychiatry'
            ,'Psychotherapy'
            ,'Sanitation'
            ,'Speech disorders'
            ,'Surgery'
            ,'Transplantology'
            ,'Traumatology'
            ,'Urology'
            ,'Veterinary medicine'
            ]
           ,['Medical appliances'
            ,'Computer tomography'
            ,'Dental implantology'
            ,'Electrophoresis'
            ,'Hearing aid'
            ,'Magnetic tomography'
            ,'Microscopy'
            ,'Radiography'
            ,'Ultrasound'
            ]
           ,['Medicine - Alternative medicine'
            ,'Acupuncture'
            ,'Homeopathy'
            ,'Manual therapy and osteopathy'
            ,'Somatics'
            ,'Traditional medicine'
            ]
           ,['Metallurgy'
            ,'Alloy addition'
            ,'Aluminium industry'
            ,'Blast-furnace practice'
            ,'Cast iron'
            ,'Continuous casting'
            ,'Electrometallurgy'
            ,'Electrothermy'
            ,'Forging'
            ,'Foundry'
            ,'Metal science'
            ,'Nonferrous industry'
            ,'Open-hearth process'
            ,'Powder metallurgy'
            ,'Roll stock'
            ,'Steel production'
            ]
           ,['Military'
            ,'Aerial photography and topography'
            ,'Air defense'
            ,'Ammunition'
            ,'Anti-air artillery'
            ,'Armored vehicles'
            ,'Artillery'
            ,'Explosives'
            ,'Fortification'
            ,'Ground forces (Army)'
            ,'Intelligence and security services'
            ,'Military aviation'
            ,'Military lingo'
            ,'Missiles'
            ,'NATO'
            ,'Navy'
            ,'Radiolocation'
            ,'Torpedoes'
            ,'Weapons of mass destruction'
            ]
           ,['Mining'
            ,'Coal'
            ,'Drilling'
            ,'Gold mining'
            ,'Mine surveying'
            ,'Mineral processing'
            ,'Ore formation'
            ,'Quarrying'
            ]
           ,['Multimedia'
            ,'Audio electronics'
            ,'Digital sound processing'
            ,'Hi-Fi'
            ,'LP players'
            ,'Projectors'
            ,'Sound recording'
            ,'Stereo'
            ,'Television'
            ,'Video recording'
            ]
           ,['Mythology'
            ,'Greek and Roman mythology'
            ,'Hinduism'
            ,'Norse mythology'
            ]
           ,['Natural resourses and wildlife conservation'
            ,'Antarctic'
            ,'Ecology'
            ,'Environment'
            ,'Forestry'
            ,'Lean production'
            ,'Taxation of forests'
            ,'Waste management'
            ,'Water resources'
            ]
           ,['Nautical'
            ,'Fishery (fishing industry)'
            ,'Foil ships'
            ,'Hovercraft'
            ,'Maritime law & Law of the Sea'
            ,'Merchant navy'
            ,'Navigation'
            ,'Navy'
            ,'Sailing ships'
            ,'Ship handling'
            ,'Shipbuilding'
            ,'Submarines'
            ,'Yachting'
            ]
           ,['Occupational health & safety'
            ,'Permit to work system'
            ,'Personal protective equipment'
            ]
           ,['Oil and gas'
            ,'Caspian'
            ,'Drilling'
            ,'Flow measurement'
            ,'Gas processing plants'
            ,'Karachaganak'
            ,'Molikpaq'
            ,'Oil / petroleum'
            ,'Oil and gas technology'
            ,'Oil processing plants'
            ,'Oilfields'
            ,'Oils and lubricants'
            ,'Sakhalin'
            ,'Sakhalin A'
            ,'Sakhalin R'
            ,'Sakhalin S'
            ,'Tengiz'
            ,'Well control'
            ]
           ,['Outdoor activities and extreme sports'
            ,'Aeronautics'
            ,'Alpine skiing'
            ,'Cycling (other than sport)'
            ,'Mountaineering'
            ,'Paragliding'
            ,'Sailing'
            ,'Scuba diving'
            ,'Skateboarding'
            ,'Skydiving'
            ,'Snowboard'
            ,'Speed skating'
            ,'Waterskiing'
            ,'Windsurfing'
            ]
           ,['Parasciences'
            ,'Astrology'
            ,'Esoterics'
            ,'Parapsychology'
            ,'Ufology'
            ]
           ,['Philology'
            ,'Palaeography'
            ,'Rhetoric'
            ]
           ,['Philosophy'
            ,'Logic'
            ]
           ,['Photography'
            ,'Film processing'
            ]
           ,['Physics'
            ,'Acoustics'
            ,'Aerodynamics'
            ,'Aerohydrodynamics'
            ,'Astrophysics'
            ,'Ballistics'
            ,'Biophysics'
            ,'Electricity'
            ,'Heat transfer'
            ,'Hydraulics'
            ,'Hydroacoustics'
            ,'Magnetics'
            ,'Mechanics'
            ,'Metal physics'
            ,'Nonlinear optics'
            ,'Nuclear physics'
            ,'Optics (branch of physics)'
            ,'Piezoelectric crystals'
            ,'Quantum electronics'
            ,'Quantum mechanics'
            ,'Solid-state physics'
            ,'Spectroscopy'
            ,'Thermodynamics'
            ,'Tribology'
            ]
           ,['Politics'
            ,'Disaster recovery'
            ,'Elections'
            ,'Foreign policy'
            ,'International relations'
            ,'Public relations'
            ]
           ,['Production'
            ,'Ceramics'
            ,'Converter industry'
            ,'Facilities'
            ,'Glass production'
            ,'Industrial hygiene'
            ,'Jewelry'
            ,'Labor organization'
            ,'Packaging'
            ,'Permit to work system'
            ,'Personal protective equipment'
            ,'Planning'
            ,'Tinware'
            ,'Trade unions'
            ]
           ,['Proper name'
            ,'Company name'
            ,'Drug name'
            ,'Given name'
            ,'Name of organization'
            ,'Names and surnames'
            ,'Surname'
            ,'Titles of works of art'
            ,'Toponym'
            ,'Trademark'
            ]
           ,['Psychology'
            ,'Ethnopsychology'
            ,'Mental health'
            ,'Neuropsychology'
            ,'Psycholinguistics'
            ,'Psychopathology'
            ,'Psychophysiology'
            ,'Psychotherapy'
            ]
           ,['Publishing'
            ,'Book binding'
            ,'Copyright'
            ,'Polygraphy'
            ,'Typography'
            ]
           ,['Quality control and standards'
            ,'GOST'
            ,'Non-destructive testing'
            ,'Reliability'
            ]
           ,['Records management'
            ,'Archiving'
            ,'Bibliography'
            ,'Office equipment'
            ,'Stationery'
            ,'Typewriters and typewriting'
            ,'Work flow'
            ]
           ,['Regional usage (other than language varieties)'
            ,'African'
            ,'American (usage, not AmE)'
            ,'Australian'
            ,'Austrian (usage)'
            ,'Belgian (usage)'
            ,'Berlin expression'
            ,'British (usage, not BrE)'
            ,'Canadian'
            ,'East-Middle-German'
            ,'Ecuador'
            ,'Eskimo (usage)'
            ,'Indonesian'
            ,'Irish (usage, not language)'
            ,'Latin American'
            ,'Local name'
            ,'Lower German'
            ,'Mexican'
            ,'Middle German'
            ,'Neapolitan'
            ,'Netherlands (usage)'
            ,'New Zealand'
            ,'North American (USA and Canada)'
            ,'Northern German'
            ,'Oriental'
            ,'Polynesian'
            ,'Puerto Rican Spanish'
            ,'Rhine'
            ,'Salvadoran Spanish'
            ,'Scottish (usage)'
            ,'Slavonic'
            ,'South African'
            ,'South German'
            ,'South-West-German'
            ,'Southern Dutch'
            ,'Swiss term'
            ,'Tuscan'
            ,'Ukrainian (usage)'
            ,'Uruguayan Spanish'
            ,'West-German'
            ]
           ,['Religion'
            ,'Bible'
            ,'Buddhism'
            ,'Catholic'
            ,'Christianity'
            ,'Clerical'
            ,'Confucianism'
            ,'Cults and miscellaneous spiritual practices'
            ,'Eastern Orthodoxy'
            ,'Hinduism'
            ,'Islam'
            ,'Judaism'
            ,'Quran'
            ,'Shinto'
            ,'Taoism'
            ]
           ,['Security systems'
            ,'Biometry'
            ,'Computer security'
            ,'Cryptography'
            ,'Identification systems'
            ,'Information security'
            ,'Infrared technology'
            ,'Signalling'
            ,'Video recording'
            ]
           ,['Service industry'
            ,'Food service and catering'
            ,'Hairdressing'
            ,'Hotel industry'
            ]
           ,['Sociology'
            ,'Survey'
            ]
           ,['Space'
            ,'Apollo-Soyuz'
            ,'Astrometry'
            ,'Astronautics'
            ,'Astronomy'
            ,'Astrophysics'
            ,'Astrospectroscopy'
            ,'Celestial mechanics'
            ,'Missiles'
            ,'NASA'
            ,'Radioastronomy'
            ,'Remote sensing'
            ]
           ,['Sports'
            ,'Acrobatics'
            ,'American football'
            ,'Archery'
            ,'Athletics'
            ,'Badminton'
            ,'Baseball'
            ,'Basketball'
            ,'Biathlon'
            ,'Billiards'
            ,'Bodybuilding'
            ,'Chess'
            ,'Croquet'
            ,'Curling'
            ,'Cycle sport'
            ,'Doping'
            ,'Equestrianism'
            ,'Fencing'
            ,'Figure skating'
            ,'Football'
            ,'Gymnastics'
            ,'Handball'
            ,'High jump'
            ,'Hockey'
            ,'Horse racing'
            ,'Kick volleyball'
            ,'Long jump'
            ,'Luge'
            ,'Petanque'
            ,'Platform diving'
            ,'Pole vaults'
            ,'Polo'
            ,'Racing and motorsport'
            ,'Rowing'
            ,'Rugby football'
            ,'Sailing'
            ,'Shooting sport'
            ,'Ski jumping'
            ,'Skiing'
            ,'Speed skating'
            ,'Sporting goods'
            ,'Swimming'
            ,'Table tennis'
            ,'Tennis'
            ,'Throw'
            ,'Trampolining'
            ,'Volleyball'
            ,'Water polo'
            ,'Weightlifting'
            ,'Yachting'
            ]
           ,['Stylistic values'
            ,'Archaic'
            ,'Barbarism'
            ,'Bookish / literary'
            ,'Business style'
            ,'Childish'
            ,'Cliche'
            ,'Epistolary'
            ,'Euphemistic'
            ,'Formal'
            ,'Invective'
            ,'Low register'
            ,'Modern use'
            ,'Neologism'
            ,'News style'
            ,'Nonstandard'
            ,'Obsolete / dated'
            ,'Officialese'
            ,'Old-fashioned'
            ,'Poetic'
            ,'Rude'
            ,'Scientific'
            ,'Slang'
            ,'Soviet'
            ,'Spoken'
            ,'Sublime'
            ,'Taboo expressions and obscenities'
            ,'Vernacular language'
            ,'Vulgar'
            ,'Written'
            ]
           ,['Subjects for Chinese dictionaries (container)'
            ,'Conventional notation'
            ,'Dragon boat'
            ,'Dragon dance'
            ,'Eastern Chinese'
            ,'Instead of'
            ,'Kabaddi'
            ,'Mahjong'
            ,'Middle Chinese'
            ,'Northeastern Mandarin'
            ,'Pigeon racing'
            ,'Verbatim'
            ]
           ,['Technology'
            ,'Accumulators'
            ,'Additive manufacturing & 3D printing'
            ,'Air conditioners'
            ,'Automated equipment'
            ,'Automatic control'
            ,'Cybernetics'
            ,'Disaster recovery'
            ,'Drives'
            ,'Extrusion'
            ,'Fiber optic'
            ,'Gyroscopes'
            ,'Household appliances'
            ,'Infrared technology'
            ,'Isolation'
            ,'Laboratory equipment'
            ,'Lasers'
            ,'Level measurement'
            ,'Lighting (other than cinema)'
            ,'Measuring instruments'
            ,'Metrology'
            ,'Microscopy'
            ,'Nanotechnology'
            ,'Photometry'
            ,'Refrigeration'
            ,'Robotics'
            ,'SAP tech.'
            ,'Sensitometry'
            ,'Switches'
            ,'Tools'
            ,'Vibration monitoring'
            ,'Welding'
            ,'Winding'
            ]
           ,['Transport'
            ,'Automobiles'
            ,'Cycling (other than sport)'
            ,'Helicopters'
            ,'International transportation'
            ,'Metro and rapid transit'
            ,'Motorcycles'
            ,'Oils and lubricants'
            ,'Public transportation'
            ,'Railway term'
            ,'Road sign'
            ,'Road traffic'
            ,'Road works'
            ,'Traffic control'
            ,'Trucks/Lorries'
            ]
           ,['Travel'
            ,'Hotel industry'
            ]
           ,['United Nations'
            ,'ICAO'
            ,'International Monetary Fund'
            ,'World trade organization'
            ]
           ,['Wellness'
            ,'Cosmetics and cosmetology'
            ,'Dietology'
            ,'Hairdressing'
            ,'Hygiene'
            ,'Perfume'
            ]
           ,['Wood, pulp and paper industries'
            ,'Logging'
            ,'Matches'
            ,'Pulp and paper industry'
            ,'Timber floating'
            ,'Wood processing'
            ]
           ]


class Groups:
    
    def __init__(self):
        self.majors = []
    
    def get_major(self,subject):
        for row in SUBJECTS:
            if subject in row:
                return row[0]
        return ''
    
    def is_major(self,subject):
        return subject in self.get_majors()
    
    def get_majors(self):
        if not self.majors:
            self.majors = [row[0] for row in SUBJECTS]
        return self.majors



class Objects:
    
    def __init__(self):
        self.groups = None
    
    def get_groups(self):
        if self.groups is None:
            self.groups = Groups()
        return self.groups


objs = Objects()
